### ISSUE TITLE
Import BUG

### ISSUE THREAD

**Issue by Masaaki-75** [showlab/Show-o#37]
Hi, i followed the README to create a new environment with all things in `requriement.txt` installed, and ran the command `accelerate launch --config_file accelerate_configs/1_gpu.yaml --main_process_port=8888 training/train.py config=configs/showo_pretraining_stage1.yaml`, but i got the following import errrors:
```
Traceback (most recent call last):
  File "/xxxx/projects/showo-main/training/train.py", line 43, in <module>
    from training.data import Text2ImageDataset
ImportError: cannot import name 'Text2ImageDataset' from 'training.data' (/opt/conda/envs/showo/lib/python3.10/site-packages/training/data.py)
```
and 
```
Traceback (most recent call last):
  File "/xxxx/projects/showo-main/training/train.py", line 43, in <module>
    from training.imagenet_dataset import ImageNetDataset
ModuleNotFoundError: No module named 'training.imagenet_dataset'
```

It seems that the folder naming has conflicts with an installed package (so weird that this package is just named `training`). How could i solve this? Thanks!

**Comment by Sierkinhane** [comment]
Can you try to uninstall `training`? We do have no dependency on such a package.

**Comment by Masaaki-75** [comment]
I was trying but i found that it is neither built in the `pip list` nor `conda env list`... I recreate the environment and rerun the command:
```
conda create -n showo python=3.10
conda activate showo
cd showo-main
pip3 install -r requirements.txt
accelerate launch --config_file accelerate_configs/1_gpu.yaml --main_process_port=8888 training/train.py config=configs/showo_pretraining_stage1.yaml
```
and still got this weird error:
```
[2024-10-07 11:25:46,156] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.2
 [WARNING]  using untested triton version (2.2.0), only 1.0.0 is known to be compatible
[2024-10-07 11:25:50,569] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.2
 [WARNING]  using untested triton version (2.2.0), only 1.0.0 is known to be compatible
Traceback (most recent call last):
  File ".../projects/showo-main/training/train.py", line 42, in <module>
    from training.data import Text2ImageDataset
ImportError: cannot import name 'Text2ImageDataset' from 'training.data' (/opt/conda/envs/showo/lib/python3.10/site-packages/training/data.py)
Traceback (most recent call last):
  File "/opt/conda/envs/showo/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/showo/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/opt/conda/envs/showo/lib/python3.10/site-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/opt/conda/envs/showo/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/envs/showo/bin/python', 'training/train.py', 'config=configs/showo_pretraining_stage1.yaml']' returned non-zero exit status 1.
```
Could this be reproduced in your machine?

**Comment by Masaaki-75** [comment]
Update: I forced to rename the funny `training` package to make it invalid. Then i got the following complaints:
```
Traceback (most recent call last):
  File "xxxx/projects/showo-main/training/train.py", line 44, in <module>
    from parquet import RefinedWebDataset
ImportError: cannot import name 'RefinedWebDataset' from 'parquet' (/opt/conda/envs/showo/lib/python3.10/site-packages/parquet/__init__.py)
```

**Comment by Sierkinhane** [comment]
Hi you can comment this import. As this function relies on internal packages, we did not release it.
